### PR TITLE
Feature filters

### LINKED ISSUE #5: Add Filters in Product Listing
- Provide functionality to Filters

### PR DESCRIPTION
**Pull request by OmKakatkar**
## Adds Filters to Product Listing Page
- Filters are by price range, category and rating.
- Sort by high-low or low-high price
- Adds data to the mock database
- Some style changes for displaying rating on cards
- Adds a product provider with access to all products from api
- Adds a files for filter constants
- Adds  a helper file for various filters
- Add to wishlist button will be shown only when user is logged in 

image
image

### CODE REVIEW

**Review by rohit8686 — APPROVED** [review]
Nice modular code and folder structure also looks good .
Looks good to merge !

**Review by lomesshh — APPROVED** [review]
clean and modular code
looks good to merge

**Review by KamiyaGaikwad — APPROVED** [review]
good folder structure and clean code. Good to merge

**Review by Nikhil-Nirmal — APPROVED** [review]
Your class naming is Top-notch keep it going.

**Pull request merged**
