### PR TITLE
Feature cart management

### LINKED ISSUE #6: Add Cart Management
- User must be able to add and remove items from the cart.
- User must be able to increase and decrease the quantity of products.
- Cart summary must reflect the changes to cart.

### PR DESCRIPTION
**Pull request by OmKakatkar**
### Product Listing Page
- `Add to cart` button on each product.
- If item exists in cart then `Show in Cart` button will be displayed

### WIshlist Page 
- `Move to Cart` button on each product.
- If item exist in cart then `Show in Cart` button will be displayed

### Cart Page
- Item can be moved to wishlist (Product will be deleted from the cart)
- Item can be removed from cart.
- Item quantity can be increased or decreased
- Total price with Delivery charges can be seen in cart summary

### Navigation Bar
- Total items in cart will be shown over the cart icon

### Media
image
image
image

### CODE REVIEW

**Review by manish591 — APPROVED** [review]
Your code is looking good to merge
I Really like: 
* Your code properly formatted and has consistent indentation
* Code is modular and easier to understand

Suggestion: 
* You can name your components file name like `Component.jsx` instead of `Component.js`.
component file should end with .jsx while pure javascript file should end with js. 
But, if you like this way you can stick with this.

**Comment by OmKakatkar** [comment]
> Your code is looking good to merge I Really like:
> 
> * Your code properly formatted and has consistent indentation
> * Code is modular and easier to understand
> 
> Suggestion:
> 
> * You can name your components file name like `Component.jsx` instead of `Component.js`.
>   component file should end with .jsx while pure javascript file should end with js.
>   But, if you like this way you can stick with this.

Thanks for the review Manish.
* First of all, I really like that you are using markdown in reviews.
* About your suggestion, I am currently keeping the file extension as it is as my editor is configured that way. Might change it in the future.

**Review by romabulani — APPROVED** [review]
- Liked the UI
- Code is clean and quite readable

Suggestion : If the user is not logged in and clicks on Add to Cart, it shows the loader on product card in current feature, instead you can navigate the user to login page or just add the toast informing him/her to login first

**Comment by OmKakatkar** [comment]
> * Liked the UI
> * Code is clean and quite readable
> 
> Suggestion : If the user is not logged in and clicks on Add to Cart, it shows the loader on product card in current feature, instead you can navigate the user to login page or just add the toast informing him/her to login first

Thanks for review Roma .
* I have updated the code to check for user login status.
* Now, the button will redirect to login page if user tries to add item to cart while logged out

**Pull request merged**
